### ISSUE TITLE
Server Crashes when Saving

### ISSUE THREAD

**Issue by GabeHasWon** [ScalarVector1/DragonLens#112]
## Replication
- Open the game
- Multiplayer -> Host and Play, any world, any settings
- Enter and exit the world
- Server will close in the background, and throw near the end of saving
With a headless server, you have to have a player join and exit the world before replication. Opening and closing a headless server will not by itself throw.
This requires only DragonLens to be enabled.

## Error
Full log: https://hst.sh/ikafejihew.sql

Relevant exception:
[12:57:19.991] [Main Thread/FATAL] [tML]: Main engine crash

Tip: This is likely a mod's fault. Disable mods one by one and check if the issue persists

System.ArgumentNullException: Value cannot be null. (Parameter 's')
   at System.ArgumentNullException.Throw(String paramName)
   at System.Text.Encoding.GetBytes(String s)
   at Terraria.ModLoader.IO.TagIO.<>c.<.cctor>b__22_17(BinaryWriter w, String v) in tModLoader\Terraria\ModLoader\IO\TagIO.cs:line 102
   at Terraria.ModLoader.IO.TagIO.PayloadHandler\`1.WriteList(BinaryWriter w, IList list) in tModLoader\Terraria\ModLoader\IO\TagIO.cs:line 55
   at Terraria.ModLoader.IO.TagIO.<>c.<.cctor>b__22_21(BinaryWriter w, IList v) in tModLoader\Terraria\ModLoader\IO\TagIO.cs:line 120
   at Terraria.ModLoader.IO.TagIO.<>c.<.cctor>b__22_24(BinaryWriter w, TagCompound v) in tModLoader\Terraria\ModLoader\IO\TagIO.cs:line 140
   at Terraria.ModLoader.IO.TagIO.<>c.<.cctor>b__22_24(BinaryWriter w, TagCompound v) in tModLoader\Terraria\ModLoader\IO\TagIO.cs:line 140
   at Terraria.ModLoader.IO.TagIO.PayloadHandler\`1.WriteList(BinaryWriter w, IList list) in tModLoader\Terraria\ModLoader\IO\TagIO.cs:line 55
   at Terraria.ModLoader.IO.TagIO.<>c.<.cctor>b__22_21(BinaryWriter w, IList v) in tModLoader\Terraria\ModLoader\IO\TagIO.cs:line 120
   at Terraria.ModLoader.IO.TagIO.<>c.<.cctor>b__22_24(BinaryWriter w, TagCompound v) in tModLoader\Terraria\ModLoader\IO\TagIO.cs:line 142
   at Terraria.ModLoader.IO.TagIO.PayloadHandler\`1.Write(BinaryWriter w, Object v) in tModLoader\Terraria\ModLoader\IO\TagIO.cs:line 41
   at Terraria.ModLoader.IO.TagIO.Write(TagCompound root, BinaryWriter writer) in tModLoader\Terraria\ModLoader\IO\TagIO.cs:line 386
   at Terraria.ModLoader.IO.TagIO.ToStream(TagCompound root, Stream stream, Boolean compress) in tModLoader\Terraria\ModLoader\IO\TagIO.cs:line 379
   at Terraria.Utilities.FileUtilities.WriteTagCompound(String path, Boolean isCloud, TagCompound tag) in tModLoader\Terraria\Utilities\FileUtilities.TML.cs:line 124
   at Terraria.ModLoader.IO.WorldIO.Save(String path, Boolean isCloudSave) in tModLoader\Terraria\ModLoader\IO\WorldIO.cs:line 61
   at Terraria.IO.WorldFile.InternalSaveWorld(Boolean useCloudSaving, Boolean resetTime) in tModLoader\Terraria\IO\WorldFile.cs:line 712
   at Terraria.IO.WorldFile.<>c__DisplayClass58_0.<SaveWorld>b__0() in tModLoader\Terraria\IO\WorldFile.cs:line 642
   at Terraria.Utilities.FileUtilities.ProtectedInvoke(Action action) in tModLoader\Terraria\Utilities\FileUtilities.cs:line 207
   at Terraria.IO.WorldFile.SaveWorld(Boolean useCloudSaving, Boolean resetTime) in tModLoader\Terraria\IO\WorldFile.cs:line 641
   at Terraria.IO.WorldFile.SaveWorld() in tModLoader\Terraria\IO\WorldFile.cs:line 617
   at Terraria.Main.DedServ_PostModLoad(Boolean& reloadMods) in tModLoader\Terraria\Main.cs:line 5181
   at Terraria.Main.DedServ() in tModLoader\Terraria\Main.cs:line 4659
   at Terraria.Program.RunGame() in tModLoader\Terraria\Program.cs:line 264

**Comment by JamzOJamz** [comment]
This pretty much renders the mod unusable in multiplayer. Should be high priority.

**Comment by steviegt6** [comment]
I can't reproduce this; can you send me the player and world files?

**Comment by steviegt6** [comment]
Actually, it seems it was fixed (band-aid) here: 26716da6c11645e06c1edc3e9a6a97a365826641

If the issue doesn't remain, please close.
