### ISSUE TITLE
Players Completely Freeze on Server

### ISSUE THREAD

**Issue by GabeHasWon** [ScalarVector1/DragonLens#114]
## Replication
1. Open the game.
2. Open a server and join it.
3. The player is completely unable to move.

## Error
Full log: https://hst.sh/bijagedire.yaml

Relevant exception: 
```
[13:24:17.607] [Main Thread/INFO] [Terraria]: Entering world with player: Spirtit, IsCloud=False, Width: 6400, Height: 1800, Evil: 1, GameMode: 2
[13:24:17.872] [Main Thread/WARN] [tML]: Silently Caught Exception: 
System.ArgumentException: An item with the same key has already been added. Key: 7f532cea-38ff-4456-9b17-230a27119103
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at DragonLens.Core.Systems.PermissionPlayer.LoadIDs()
   at DragonLens.Core.Systems.PermissionPlayer.OnEnterWorld()
   at Terraria.ModLoader.PlayerLoader.OnEnterWorld(Int32 playerIndex)
   at Terraria.Player.Hooks.EnterWorld(Int32 playerIndex)
   at DMD<System.Void Terraria.Player:Spawn(Terraria.PlayerSpawnContext)>(Player this, PlayerSpawnContext context)
   at NewBeginnings.Common.PlayerBackgrounds.PlayerBackgroundPlayer.HijackSpawn(orig_Spawn orig, Player self, PlayerSpawnContext context)
   at Hook<System.Void NewBeginnings.Common.PlayerBackgrounds.PlayerBackgroundPlayer::HijackSpawn(Terraria.On_Player+orig_Spawn,Terraria.Player,Terraria.PlayerSpawnContext)>(Player , PlayerSpawnContext )
   at SyncProxy<System.Void Terraria.Player:Spawn(Terraria.PlayerSpawnContext)>(Player , PlayerSpawnContext )
   at Terraria.MessageBuffer.GetData(Int32 start, Int32 length, Int32& messageType)
   at Terraria.NetMessage.CheckBytes(Int32 bufferIndex)
   at DMD<System.Void Terraria.Main:DoUpdate(Microsoft.Xna.Framework.GameTime&)>(Main this, GameTime& gameTime)
   at DragonLens.Content.Tools.Gameplay.FastForwardSystem.UpdateExtraTimes(orig_DoUpdate orig, Main self, GameTime& gameTime)
   at Hook<System.Void DragonLens.Content.Tools.Gameplay.FastForwardSystem::UpdateExtraTimes(Terraria.On_Main+orig_DoUpdate,Terraria.Main,Microsoft.Xna.Framework.GameTime&)>(Main , GameTime& )
   at SyncProxy<System.Void Terraria.Main:DoUpdate(Microsoft.Xna.Framework.GameTime&)>(Main , GameTime& )
   at Terraria.Main.Update(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.Tick()
   at Microsoft.Xna.Framework.Game.RunLoop()
   at Microsoft.Xna.Framework.Game.Run()
   at Terraria.Program.RunGame()
   at Terraria.Program.LaunchGame_(Boolean isServer)
   at Terraria.Program.LaunchGame(String[] args, Boolean monoArgs)
   at Terraria.MonoLaunch.Main_End(String[] args)
   at Terraria.MonoLaunch.<>c__DisplayClass1_0.<Main>b__1()
```

**Comment by steviegt6** [comment]
Presumably fixed in 318b15eb9d6f822d4281ed41cdc961cc8fe3ac4c, please re-open or file a new ticket if the issue persists.
